'use strict';
const $=id=>document.getElementById(id),chains=['Ethereum','Polygon','BNB Chain','Bitcoin','Tron'];
let user,overview,network,eventOffset=0;
const node=(tag,text)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=String(text);return n;};
function notice(text,error=false){$('notice').textContent=text;$('notice').className=error?'error':'';}
async function api(path,options={}){const r=await fetch(path,{credentials:'same-origin',...options,headers:{'Content-Type':'application/json','X-CSRF-Token':user?.csrf||'',...options.headers}});const d=await r.json();if(!r.ok){if(r.status===401){location.href='/';throw Error('Sign in required');}throw Error(typeof d.detail==='string'?d.detail:JSON.stringify(d.detail));}return d;}
function action(id,fn){$(id).addEventListener($(id).tagName==='FORM'?'submit':'click',async e=>{e.preventDefault();const b=e.submitter||$(id);b.disabled=true;try{await fn();}catch(err){notice(err.message,true);}finally{b.disabled=false;}});}
function table(id,headers,rows){const t=node('table'),head=node('tr');headers.forEach(x=>head.append(node('th',x)));t.append(head);for(const cells of rows){const tr=node('tr');for(const c of cells){const td=node('td');td.append(c instanceof Node?c:node('span',typeof c==='object'?JSON.stringify(c):c??'—'));tr.append(td);}t.append(tr);}const wrap=node('div');wrap.className='table-wrap';wrap.append(t);$(id).replaceChildren(rows.length?wrap:node('p','No records yet.'));}
function button(text,fn){const b=node('button',text);b.onclick=async()=>{b.disabled=true;try{await fn();}catch(e){notice(e.message,true);}finally{b.disabled=false;}};return b;}
function details(title,data){const d=node('details');d.append(node('summary',title),node('pre',JSON.stringify(data,null,2)));return d;}
function selectedCase(){const id=$('caseSelect').value;if(!id)throw Error('Select a case first');return encodeURIComponent(id);}
async function refreshCases(){const data=await api('/cases');const old=$('caseSelect').value;$('caseSelect').replaceChildren(...data.map(c=>{const o=node('option',c.case_id+' · '+c.fraud_type);o.value=c.case_id;return o;}));if(data.some(c=>c.case_id===old))$('caseSelect').value=old;}
function color(n){if(n.type==='reported_wallet')return '#8645b4';if(n.is_mixer)return '#875830';if(n.is_vasp)return '#161b22';const s=n.risk_score;return s==null?'#8da2b3':s>=80?'#e84258':s>=50?'#f38633':s>=20?'#edbe20':'#0eaa82';}
function renderGraph(){if(!overview)return;const chain=$('filterChain').value,q=$('filterText').value.toLowerCase(),risk=Number($('filterRisk').value);const keep=overview.nodes.filter(n=>(!chain||n.chain===chain)&&(!q||(n.address+' '+(n.entity_name||'')).toLowerCase().includes(q))&&(risk===0||(n.risk_score??-1)>=risk));const ids=new Set(keep.map(n=>n.id));const visible=keep.slice(0,2000);if(keep.length>2000)notice('Graph limited to 2,000 nodes. Narrow filters; indexed events remain searchable.');ids.clear();visible.forEach(n=>ids.add(n.id));const ns=visible.map(n=>({id:n.id,label:n.chain,shape:n.type==='transaction'?'diamond':'dot',color:color(n),size:n.type==='reported_wallet'?17:10}));const es=overview.edges.filter(e=>ids.has(e.chain+':'+e.from)&&ids.has(e.chain+':'+e.to)).map(e=>({id:e.id,from:e.chain+':'+e.from,to:e.chain+':'+e.to,arrows:'to',color:'#a7bdce',data:e}));for(const [i,l] of [...overview.links.map(x=>x.payload),...overview.candidates].entries()){const from=l.from_chain+':'+l.from_address,to=l.to_chain+':'+l.to_address;if(ids.has(from)&&ids.has(to))es.push({id:'cross-'+i,from,to,dashes:true,arrows:'to',color:l.kind==='bridge_provider_link'?'#1175b5':'#dc9027',data:l});}
if(network)network.destroy();network=new vis.Network($('graph'),{nodes:ns,edges:es},{interaction:{hover:true},physics:{solver:'barnesHut',barnesHut:{gravitationalConstant:-4000,springLength:130,avoidOverlap:.8},stabilization:{iterations:180}},nodes:{font:{size:10}},edges:{smooth:{type:'continuous'}}});network.on('stabilizationIterationsDone',()=>network.setOptions({physics:false}));network.on('click',p=>{const n=keep.find(n=>n.id===p.nodes[0]);const e=es.find(e=>e.id===p.edges[0]);$('inspection').textContent=JSON.stringify(n||e?.data||{},null,2);});}
async function loadCase(){overview=await api('/workspace/cases/'+selectedCase()+'/overview');$('scope').textContent=overview.scope;renderGraph();$('analysis').replaceChildren(...overview.traces.map(t=>details(t.chain+' · '+t.wallet+' · ML: '+(t.ml?.status||'not recorded'),t)));$('links').replaceChildren(...overview.links.map(l=>details('Bridge-provider link',l)),...overview.candidates.map(l=>details('Unverified amount/time candidate',l)));if(!overview.links.length&&!overview.candidates.length)$('links').append(node('p','No links found. Candidate matching requires reviewed bridge and asset mappings.'));$('rawEvidence').replaceChildren(...[...new Set(overview.traces.flatMap(t=>t.raw_evidence_refs||[]))].map(ref=>button('Download '+ref.slice(0,12)+'…',async()=>download('evidence-'+ref+'.json',await api('/workspace/cases/'+selectedCase()+'/evidence/'+ref)))));await loadEvents();notice('Case loaded. Scores are triage indicators, not fraud probabilities.');}
async function loadEvents(){const q=new URLSearchParams({chain:$('eventChain').value,wallet:$('eventWallet').value,asset:$('eventAsset').value,offset:eventOffset});if($('eventStart').value)q.set('start',new Date($('eventStart').value).toISOString());if($('eventEnd').value)q.set('end',new Date($('eventEnd').value).toISOString());const rows=await api('/workspace/cases/'+selectedCase()+'/events?'+q);table('events',['Chain','Transaction','From','To','Amount / asset','Time'],rows.map(r=>[r.blockchain,r.tx_hash,r.sender,r.receiver,r.payload.value+' '+r.payload.asset,r.occurred_at]));$('prevEvents').disabled=eventOffset===0;$('nextEvents').disabled=rows.length<200;}
async function jobs(){const rows=await api('/workspace/jobs');table('jobList',['Case','Job','State','Result / error','Action'],rows.map(j=>[j.case_id,j.id,j.state,j.result||j.error||'',j.state==='failed'?button('Retry',async()=>{await api('/workspace/jobs/'+j.id+'/retry',{method:'POST'});await jobs();}):'']));}
async function monitor(){const [w,a]=await Promise.all([api('/workspace/watchlists'),api('/workspace/alerts')]);table('watches',['Case','Chain / wallet','Interval','Baseline','Enabled','Action'],w.map(w=>[w.case_id,w.blockchain+' '+w.wallet_address,w.interval_seconds+'s',w.baseline_set,w.enabled,w.enabled?button('Disable',async()=>{await api('/workspace/watchlists/'+w.id,{method:'DELETE'});await monitor();}):'']));table('alerts',['Case','Severity','Detected','Evidence','Status'],a.map(a=>[a.case_id,a.severity,a.created_at,details(a.payload.message||a.payload.trigger||'Alert',a.payload),a.acknowledged_at?'Acknowledged':button('Acknowledge',async()=>{await api('/workspace/alerts/'+a.id+'/acknowledge',{method:'POST'});await monitor();})]));}
function download(name,data){const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const a=node('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
for(const s of document.querySelectorAll('select.chain,#filterChain,#eventChain'))for(const c of chains){const o=node('option',c);o.value=c;s.append(o);}
for(const b of document.querySelectorAll('[data-page]'))b.onclick=()=>{document.querySelectorAll('.page').forEach(p=>p.hidden=p.id!==b.dataset.page);if(b.dataset.page==='cases'&&network)requestAnimationFrame(()=>{network.redraw();network.fit();});};
action('loadCase',loadCase);action('filterGraph',renderGraph);action('fit',()=>network?.fit());action('printCase',()=>{if(!overview)throw Error('Open a case first');const ds=[...document.querySelectorAll('#cases details')];const states=ds.map(d=>d.open);ds.forEach(d=>d.open=true);window.print();ds.forEach((d,i)=>d.open=states[i]);});
action('exportCase',async()=>download('CryptoTrace-case-export.json',await api('/workspace/cases/'+selectedCase()+'/export')));
action('walletForm',async()=>{const r=await api('/workspace/cases/'+selectedCase()+'/wallets',{method:'POST',body:JSON.stringify({blockchain:$('walletChain').value,wallet_address:$('walletAddress').value,max_hops:Number($('walletHops').value)})});notice('Queued job '+r.job_id+'. Check Background jobs, then reopen the case.');});
action('complaintForm',async()=>{const body={case_id:$('newCase').value,victim_reference:$('victim').value,complaint_reference:$('complaintRef').value,fraud_type:$('fraud').value,reported_amount:$('amount').value,currency:$('currency').value,incident_date:new Date($('incident').value).toISOString(),evidence:$('evidence').value.split('\n').filter(Boolean),wallets:[{blockchain:$('intakeChain').value,wallet_address:$('intakeWallet').value,max_hops:2}]};const r=await api('/workspace/complaints',{method:'POST',body:JSON.stringify(body)});await refreshCases();notice('Created '+r.case_id+'; queued '+r.jobs.length+' trace.');});
action('importCase',async()=>{const f=$('importFile').files[0];if(!f||f.size>100000)throw Error('Select a JSON file under 100 KB');const d=JSON.parse(await f.text());const r=await api('/workspace/complaints',{method:'POST',body:JSON.stringify(d)});await refreshCases();notice('Imported '+r.case_id);});
action('watchForm',async()=>{await api('/workspace/cases/'+encodeURIComponent($('watchCase').value)+'/watchlists',{method:'POST',body:JSON.stringify({blockchain:$('watchChain').value,wallet_address:$('watchWallet').value,interval_seconds:Number($('watchInterval').value),threshold:Number($('watchThreshold').value)})});await monitor();notice('Watch enabled. Keep the worker running.');});
action('refreshJobs',jobs);action('refreshMonitor',monitor);action('eventForm',async()=>{eventOffset=0;await loadEvents();});action('nextEvents',async()=>{eventOffset+=200;await loadEvents();});action('prevEvents',async()=>{eventOffset=Math.max(0,eventOffset-200);await loadEvents();});
action('bridgeForm',async()=>{const r=await api('/workspace/cases/'+selectedCase()+'/bridge-lookup',{method:'POST',body:JSON.stringify({blockchain:$('bridgeChain').value,tx_hash:$('bridgeTx').value})});await loadCase();notice('Bridge lookup: '+r.status);});
action('assetForm',async()=>{await api('/workspace/registry/assets',{method:'POST',body:JSON.stringify({blockchain:$('assetChain').value,asset_id:$('assetId').value,canonical_asset:$('assetKey').value,source:$('assetSource').value})});notice('Asset mapping saved');});
action('registryBridgeForm',async()=>{await api('/workspace/registry/bridges',{method:'POST',body:JSON.stringify({blockchain:$('registryChain').value,wallet_address:$('registryAddress').value,name:$('registryName').value,source:$('registrySource').value})});notice('Bridge endpoint saved');});
action('loadSchema',async()=>{$('schema').textContent=JSON.stringify(await api('/workspace/integration'),null,2);});
(async()=>{try{user=await api('/auth/me');$('identity').textContent=user.username+' · '+user.role;for(const id of ['assetForm','registryBridgeForm'])$(id).hidden=user.role!=='admin';await refreshCases();notice('Ready. Open a case or create a complaint.');}catch(e){notice(e.message,true);}})();

action('mlStatus',async()=>{$('mlStatusText').textContent=JSON.stringify(await api('/workspace/ml/status'),null,2);});
action('exportFeatures',async()=>download('CryptoTrace-features.json',await api('/workspace/cases/'+selectedCase()+'/features')));

action('loadRegistry',async()=>{$('registryData').textContent=JSON.stringify(await api('/workspace/registry'),null,2);});
